@startuml

title __RINEXFILELOGGER's Class Diagram__\n

  namespace com.whu.gnss.gnsslogger {
    namespace rinexFileLogger {
      class com.whu.gnss.gnsslogger.rinexFileLogger.Rinex {
          {static} - TAG : String
          - context : Context
          - line : char[]
          - out : FileWriter
          - ver : int
          + Rinex()
          + closeFile()
          + setFileWriter()
          + writeBody()
          + writeHeader()
          - createFile()
          - resetLine()
          - writeLine()
      }
    }
  }
  

  namespace com.whu.gnss.gnsslogger {
    namespace rinexFileLogger {
      class com.whu.gnss.gnsslogger.rinexFileLogger.RinexHeader {
          - antennaEccentricityEast : double
          - antennaEccentricityNorth : double
          - antennaHeight : double
          - antennaNumber : String
          - antennaType : String
          - cartesianX : String
          - cartesianY : String
          - cartesianZ : String
          - markName : String
          - markType : String
          - observerAgencyName : String
          - observerName : String
          - receiverNumber : String
          - receiverType : String
          - receiverVersion : String
          + RinexHeader()
          + getAntennaEccentricityEast()
          + getAntennaEccentricityNorth()
          + getAntennaHeight()
          + getAntennaNumber()
          + getAntennaType()
          + getCartesianX()
          + getCartesianY()
          + getCartesianZ()
          + getGpsTime()
          + getMarkName()
          + getMarkType()
          + getObserverAgencyName()
          + getObserverName()
          + getReceiverNumber()
          + getReceiverType()
          + getReceiverVersion()
      }
    }
  }
  

  namespace com.whu.gnss.gnsslogger {
    namespace rinexFileLogger {
      class com.whu.gnss.gnsslogger.rinexFileLogger.RinexNav {
          {static} - TAG : String
          - context : Context
          - outNav : FileWriter
          - ver : int
          + RinexNav()
          + closeFile()
          + setFileWriter()
          + writeBody()
          + writeHeader()
          - createFile()
      }
    }
  }
  

  com.whu.gnss.gnsslogger.rinexFileLogger.RinexHeader o-- com.whu.gnss.gnsslogger.constellations.GpsTime : gpsTime


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
